version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - appnet
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - appnet
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - appnet
networks:
  appnet:
