version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: auth_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: auth_app

  backend:
    build: ./backend
    container_name: auth_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 8080

  frontend:
    build: ./frontend
    container_name: auth_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  mongodb_data: